curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/jump-32.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/energy.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/combo-32.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/dead-32.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/btn.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/fly.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/friend.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/time1.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/score1.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/in1.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/out1.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/bg1.mp3
curl -O https: //wximg.qq.com/wxgame/bottlefly/xingji/music/start-32.mp3
